# Generated by Django 4.1.7 on 2023-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_seguros', '0002_alter_cliente_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='domicilio_depto',
            field=models.CharField(max_length=128, null=True, verbose_name='Depto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_calle',
            field=models.CharField(default=0, max_length=128, verbose_name='Calle'),
            preserve_default=False,
        ),
    ]
