# Generated by Django 4.1.7 on 2023-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_seguros', '0003_cliente_domicilio_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_depto',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Depto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre o Razón Social'),
        ),
    ]
