# Generated by Django 4.1.7 on 2023-05-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_seguros', '0004_alter_cliente_domicilio_depto_alter_cliente_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='aseugrado',
            new_name='asegurado',
        ),
    ]
